name: Deploy Trainer App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          source /root/seniorProj/venv/bin/activate
          pip install -r requirements.txt

      - name: Restart the app service
        run: sudo systemctl restart trainer-app